# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgoods.proto\x12\x05goods\x1a\x1bgoogle/protobuf/empty.proto\"\x8e\x02\n\x05Goods\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\ngoods_code\x18\x02 \x01(\t\x12\x12\n\ngoods_name\x18\x03 \x01(\t\x12\x12\n\ngoods_desc\x18\x04 \x01(\t\x12\x14\n\x0cgoods_weight\x18\x05 \x01(\x02\x12\x0f\n\x07goods_w\x18\x06 \x01(\x02\x12\x0f\n\x07goods_d\x18\x07 \x01(\x02\x12\x0f\n\x07goods_h\x18\x08 \x01(\x02\x12\x12\n\ngoods_unit\x18\t \x01(\t\x12\x13\n\x0bgoods_class\x18\n \x01(\t\x12\x13\n\x0bgoods_brand\x18\x0b \x01(\t\x12\x13\n\x0bgoods_color\x18\x0c \x01(\t\x12\x10\n\x08\x62\x61r_code\x18\r \x01(\t\x12\x0f\n\x07partial\x18\x0e \x01(\x08\"\x12\n\x10GoodsListRequest\"\"\n\x14GoodsRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\'\n\x11GoodsQueryRequest\x12\x12\n\npublish_id\x18\x01 \x01(\t2\xb5\x02\n\x0fGoodsController\x12\x31\n\x04List\x12\x17.product.GoodsListRequest\x1a\x0c.product.Goods\"\x00\x30\x01\x12&\n\x06\x43reate\x12\x0c.product.Goods\x1a\x0c.product.Goods\"\x00\x12\x37\n\x08Retrieve\x12\x1b.product.GoodsRetrieveRequest\x1a\x0c.product.Goods\"\x00\x12&\n\x06Update\x12\x0c.product.Goods\x1a\x0c.product.Goods\"\x00\x12\x31\n\x07\x44\x65stroy\x12\x0c.product.Goods\x1a\x16.google.protobuf.Empty\"\x00\x12\x33\n\x05Query\x12\x18.product.GoodsQueryRequest\x1a\x0c.product.Goods\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'goods_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GOODS._serialized_start=52
  _GOODS._serialized_end=322
  _GOODSLISTREQUEST._serialized_start=324
  _GOODSLISTREQUEST._serialized_end=342
  _GOODSRETRIEVEREQUEST._serialized_start=344
  _GOODSRETRIEVEREQUEST._serialized_end=378
  _GOODSQUERYREQUEST._serialized_start=380
  _GOODSQUERYREQUEST._serialized_end=419
  _GOODSCONTROLLER._serialized_start=422
  _GOODSCONTROLLER._serialized_end=731
# @@protoc_insertion_point(module_scope)
