# Generated by Django 4.1.1 on 2022-10-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "merchant_type",
                    models.CharField(
                        choices=[("shopee", "shopee category")],
                        default="shopee",
                        max_length=16,
                        verbose_name="Shopee Category merchant id",
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(
                        max_length=64, verbose_name="Shopee Category merchant id"
                    ),
                ),
                (
                    "category_id",
                    models.IntegerField(default=0, verbose_name="Shopee Category ID"),
                ),
            ],
            options={
                "verbose_name": "product_category",
                "verbose_name_plural": "Product Category",
                "db_table": "product_category",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategoryBrand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                ("brand_id", models.IntegerField(default=0, verbose_name="Brand ID")),
                (
                    "display_brand_name",
                    models.CharField(max_length=64, verbose_name="Brand Name"),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ProductLogistic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "product_w",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Product Width"
                    ),
                ),
                (
                    "product_h",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Product Height"
                    ),
                ),
                (
                    "product_d",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Product Depth"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Product Weight"
                    ),
                ),
                (
                    "days_deliver",
                    models.IntegerField(
                        blank=True, default=3, verbose_name="Day to delivery"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_logistic",
                        to="store.storeproductmodel",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product_logistic",
                "verbose_name_plural": "Product Logistic",
                "db_table": "product_logistic",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategoryAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "attribute_id",
                    models.CharField(
                        max_length=64, verbose_name="Category Attribute id"
                    ),
                ),
                (
                    "display_value_name",
                    models.CharField(
                        max_length=32, verbose_name="Category Attribute value"
                    ),
                ),
                (
                    "value_id",
                    models.IntegerField(default=-1, verbose_name="Attribute Value Id"),
                ),
                (
                    "multiple",
                    models.BooleanField(default=False, verbose_name="Is Multiple"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="publish.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "product_category_attribute",
                "verbose_name_plural": "Product Category attribute",
                "db_table": "product_category_attribute",
                "ordering": ["-create_time"],
            },
        ),
        migrations.AddField(
            model_name="productcategory",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brand_category",
                to="publish.productcategorybrand",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_category",
                to="store.storeproductmodel",
                verbose_name="Product Price Info",
            ),
        ),
        migrations.CreateModel(
            name="GlobalProductTier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "global_product_id",
                    models.CharField(max_length=128, verbose_name="Global Product Id"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopee_product",
                        to="store.storeproductmodel",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_store",
                        to="store.storemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "global_product_tier",
                "verbose_name_plural": "Global Product Tier",
                "db_table": "global_product_tier",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ProductEditPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "store_id",
                    models.CharField(max_length=64, verbose_name="The price of Shop"),
                ),
                (
                    "current_price",
                    models.FloatField(default=0, verbose_name="Current price"),
                ),
                (
                    "original_price",
                    models.FloatField(default=0, verbose_name="Original price"),
                ),
                ("currency", models.CharField(max_length=32, verbose_name="Currency")),
                ("discount_id", models.BigIntegerField(default=0, verbose_name="活动ID")),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Is Price Publish"),
                ),
                (
                    "publish_ready",
                    models.BooleanField(
                        default=False, verbose_name="Is Price Publish Ready"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_info",
                        to="store.storeproductmodel",
                        verbose_name="Product Price Info",
                    ),
                ),
            ],
            options={
                "verbose_name": "product_edit_price",
                "db_table": "product_edit_price",
                "ordering": ["-create_time"],
                "unique_together": {("product_id", "store_id")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="productcategory",
            unique_together={("product_id", "merchant_type", "merchant_id")},
        ),
    ]
