# Generated by Django 4.1.1 on 2022-11-02 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publish", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="GlobalProductTier",),
    ]
