# Generated by Django 4.1.1 on 2022-11-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_storemodel_merchant"),
        ("publish", "0002_delete_globalproducttier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category",
                to="store.storeproductmodel",
                verbose_name="Product Price Info",
            ),
        ),
        migrations.AlterField(
            model_name="producteditprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edit_price",
                to="store.storeproductvariantmodel",
                verbose_name="Product Price Info",
            ),
        ),
        migrations.CreateModel(
            name="ProductOptionConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "stock_qty",
                    models.IntegerField(default=0, verbose_name="Model Stock"),
                ),
                ("price", models.FloatField(default=0, verbose_name="Model Price")),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_stocks",
                        to="store.storeproductmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "globalproduct_model_stock",
                "verbose_name_plural": "Global Product Model Stock",
                "db_table": "globalproduct_model_stock",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ProductMediaPublish",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(
                        max_length=64, verbose_name="Product Media merchant id"
                    ),
                ),
                (
                    "publish_id",
                    models.CharField(
                        max_length=128, verbose_name="Product Media Publish id"
                    ),
                ),
                (
                    "publish_url",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Product Meida Publish Url",
                    ),
                ),
                (
                    "source_url",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Product Meida Source Url",
                    ),
                ),
            ],
            options={
                "verbose_name": "product_media_publish",
                "db_table": "product_media_publish",
                "ordering": ["-create_time"],
                "unique_together": {("publish_id",)},
            },
        ),
    ]
