# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: supplier.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esupplier.proto\x12\x08supplier\"\xaa\x01\n\x08Supplier\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rsupplier_name\x18\x02 \x01(\t\x12\x15\n\rsupplier_city\x18\x03 \x01(\t\x12\x18\n\x10supplier_address\x18\x04 \x01(\t\x12\x18\n\x10supplier_contact\x18\x05 \x01(\t\x12\x18\n\x10supplier_manager\x18\x06 \x01(\t\x12\x16\n\x0esupplier_level\x18\x07 \x01(\t\"\x8b\x01\n\x0cPurchasePlan\x12\n\n\x02id\x18\x01 \x01(\x05\x12$\n\x08supplier\x18\x02 \x01(\x0b\x32\x12.supplier.Supplier\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x11\n\timage_url\x18\x05 \x01(\t\x12\x0b\n\x03tag\x18\x06 \x01(\t\x12\r\n\x05goods\x18\x07 \x03(\x05\"d\n\x0fPurchaseSetting\x12\n\n\x02id\x18\x01 \x01(\x05\x12$\n\x04plan\x18\x02 \x01(\x0b\x32\x16.supplier.PurchasePlan\x12\x10\n\x08goods_id\x18\x03 \x01(\x05\x12\r\n\x05level\x18\x04 \x01(\x05\"!\n\x13SupplierListRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"[\n\x08Response\x12\x1c\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x0e.supplier.Code\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12$\n\x08supplier\x18\x03 \x01(\x0b\x32\x12.supplier.Supplier*Z\n\x04\x43ode\x12\n\n\x06UNKNOW\x10\x00\x12\x16\n\x12SUPPLIER_NOT_FOUND\x10\x01\x12\x16\n\x12ILLEGAL_PARAMETERS\x10\x03\x12\x16\n\x12MISSING_PARAMETERS\x10\x04\x32\xf9\x02\n\x12SupplierController\x12=\n\x04List\x12\x1d.supplier.SupplierListRequest\x1a\x12.supplier.Supplier\"\x00\x30\x01\x12\x32\n\x06\x43reate\x12\x12.supplier.Supplier\x1a\x12.supplier.Response\"\x00\x12?\n\x08Retrieve\x12\x1d.supplier.SupplierListRequest\x1a\x12.supplier.Response\"\x00\x12\x32\n\x06Update\x12\x12.supplier.Supplier\x1a\x12.supplier.Response\"\x00\x12\x33\n\x07\x44\x65stroy\x12\x12.supplier.Supplier\x1a\x12.supplier.Response\"\x00\x12\x46\n\x12\x43reatePurchasePlan\x12\x16.supplier.PurchasePlan\x1a\x16.supplier.PurchasePlan\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'supplier_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CODE._serialized_start=573
  _CODE._serialized_end=663
  _SUPPLIER._serialized_start=29
  _SUPPLIER._serialized_end=199
  _PURCHASEPLAN._serialized_start=202
  _PURCHASEPLAN._serialized_end=341
  _PURCHASESETTING._serialized_start=343
  _PURCHASESETTING._serialized_end=443
  _SUPPLIERLISTREQUEST._serialized_start=445
  _SUPPLIERLISTREQUEST._serialized_end=478
  _RESPONSE._serialized_start=480
  _RESPONSE._serialized_end=571
  _SUPPLIERCONTROLLER._serialized_start=666
  _SUPPLIERCONTROLLER._serialized_end=1043
# @@protoc_insertion_point(module_scope)
