# Generated by Django 4.1.1 on 2022-10-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ListModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "parents_class_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        null=True,
                        verbose_name="Goods Parents Class IDS",
                    ),
                ),
                (
                    "goods_class",
                    models.CharField(max_length=32, verbose_name="Goods Class"),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "goodsclass",
                "ordering": ["goods_class"],
            },
        ),
        migrations.CreateModel(
            name="ShopeeAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "category_id",
                    models.IntegerField(default=0, verbose_name="Shopee Category ID"),
                ),
                (
                    "attribute_id",
                    models.CharField(max_length=64, verbose_name="Shopee Attribute id"),
                ),
                (
                    "original_attribute_name",
                    models.CharField(
                        max_length=256, verbose_name="Shopee Attribute Name"
                    ),
                ),
                (
                    "display_attribute_name",
                    models.CharField(
                        max_length=256, verbose_name="Shopee Attribute Display Name"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="Is mandatory"),
                ),
                (
                    "input_validation_type",
                    models.CharField(
                        choices=[
                            ("INT_TYPE", "int_type"),
                            ("STRING_TYPE", "string_type"),
                            ("ENUM_TYPE", "enum_type"),
                            ("FLOAT_TYPE", "float_type"),
                            ("DATE_TYPE", "date_type"),
                            ("TIMESTAMP_TYPE", "timestamp_type"),
                            ("NO_VALIDATE_TYPE", "no_validate_type"),
                        ],
                        default="STRING_TYPE",
                        max_length=32,
                        verbose_name="Shopee Attribute input validate type",
                    ),
                ),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("NORMAL", "normal"),
                            ("QUANTITATIVE", "quantitative"),
                        ],
                        default="NORMAL",
                        max_length=16,
                    ),
                ),
                (
                    "date_format_type",
                    models.CharField(
                        choices=[
                            ("YEAR_MONTH_DATE", "year_month_date"),
                            ("YEAR_MONTH", "year_month"),
                        ],
                        default="YEAR_MONTH_DATE",
                        max_length=32,
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("DROP_DOWN", "drop_down"),
                            ("MULTIPLE_SELECT", "multiple_select"),
                            ("TEXT_FILED", "text_filed"),
                            ("COMBO_BOX", "combo_box"),
                            ("MULTIPLE_SELECT_COMBO_BOX", "multiple_select_combo_box"),
                        ],
                        default="DROP_DOWN",
                        max_length=32,
                    ),
                ),
                (
                    "attribute_unit",
                    models.JSONField(
                        default=[], max_length=64, verbose_name="attribute unit"
                    ),
                ),
            ],
            options={
                "verbose_name": "shopee_attribute",
                "verbose_name_plural": "Shopee attribute",
                "db_table": "shopee_attribute",
                "ordering": ["-create_time"],
                "unique_together": {("openid", "category_id", "attribute_id")},
            },
        ),
        migrations.CreateModel(
            name="ShopeeCategoryTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(
                        max_length=64, verbose_name="Shopee Category merchant id"
                    ),
                ),
                (
                    "category_id",
                    models.IntegerField(default=0, verbose_name="Shopee Category ID"),
                ),
                ("brand_id", models.IntegerField(default=0, verbose_name="Brand ID")),
                (
                    "display_brand_name",
                    models.CharField(max_length=64, verbose_name="Brand Name"),
                ),
                (
                    "template_name",
                    models.CharField(
                        max_length=64, verbose_name="Shopee Category templaate name"
                    ),
                ),
            ],
            options={
                "verbose_name": "shopee_category_template",
                "verbose_name_plural": "Shopee Category Template",
                "db_table": "shopee_category_template",
                "ordering": ["-create_time"],
                "unique_together": {("merchant_id", "template_name")},
            },
        ),
        migrations.CreateModel(
            name="ShopeeCategoryTemplateAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "attribute_id",
                    models.CharField(
                        max_length=64, verbose_name="Category Attribute id"
                    ),
                ),
                (
                    "display_value_name",
                    models.CharField(
                        max_length=32, verbose_name="Category Attribute value"
                    ),
                ),
                (
                    "value_id",
                    models.IntegerField(default=-1, verbose_name="Attribute Value Id"),
                ),
                (
                    "multiple",
                    models.BooleanField(default=False, verbose_name="Is Multiple"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="category.shopeecategorytemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "shopee_category_template_attribute",
                "verbose_name_plural": "Shopee Category Template Attribute",
                "db_table": "shopee_category_template_attribute",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="ShopeeCategoryBrand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(
                        max_length=64, verbose_name="Shopee Category merchant id"
                    ),
                ),
                (
                    "category_id",
                    models.IntegerField(default=0, verbose_name="Shopee Category ID"),
                ),
                (
                    "brand_id",
                    models.IntegerField(default=0, verbose_name="Shopee Brand ID"),
                ),
                (
                    "original_brand_name",
                    models.CharField(max_length=64, verbose_name="Shopee Brand Name"),
                ),
                (
                    "display_brand_name",
                    models.CharField(
                        max_length=64, verbose_name="Shopee Brand Display Name"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="Is mandatory"),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("DROP_DOWN", "drop_down"),
                            ("MULTIPLE_SELECT", "multiple_select"),
                            ("TEXT_FILED", "text_filed"),
                            ("COMBO_BOX", "combo_box"),
                            ("MULTIPLE_SELECT_COMBO_BOX", "multiple_select_combo_box"),
                        ],
                        default="DROP_DOWN",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "shopee_category_brand",
                "verbose_name_plural": "Shopee Category Brand",
                "db_table": "shopee_category_brand",
                "ordering": ["-create_time"],
                "unique_together": {
                    ("openid", "merchant_id", "category_id", "brand_id")
                },
            },
        ),
        migrations.CreateModel(
            name="ShopeeCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(
                        max_length=64, verbose_name="Shopee Category merchant id"
                    ),
                ),
                (
                    "category_id",
                    models.IntegerField(default=0, verbose_name="Shopee Category ID"),
                ),
                (
                    "original_category_name",
                    models.CharField(
                        max_length=256,
                        verbose_name="Shopee Category Original Display Name",
                    ),
                ),
                (
                    "display_category_name",
                    models.CharField(
                        max_length=256, verbose_name="Shopee Category Display Name"
                    ),
                ),
                (
                    "has_children",
                    models.BooleanField(default=False, verbose_name="Has Children"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SUB_CATEGORY",
                        to="category.shopeecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "shopee_category",
                "verbose_name_plural": "Shopee Category",
                "db_table": "shopeecategory",
                "ordering": ["-create_time"],
                "unique_together": {("openid", "merchant_id", "category_id")},
            },
        ),
        migrations.CreateModel(
            name="ShopeeAttributeValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "value_id",
                    models.IntegerField(verbose_name="Shopee Attribute Value Id"),
                ),
                (
                    "original_value_name",
                    models.CharField(
                        max_length=64, verbose_name="Shopee Attribute Value Name"
                    ),
                ),
                (
                    "display_value_name",
                    models.CharField(
                        max_length=128, verbose_name="Shopee Attribute Display Name"
                    ),
                ),
                (
                    "value_unit",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=64,
                        null=True,
                        verbose_name="Shopee Attribute Unit",
                    ),
                ),
                (
                    "parent_attribute_list",
                    models.JSONField(
                        default=[],
                        max_length=256,
                        verbose_name="Parent Attribute List([parent_attribute_id, parent_value_id])",
                    ),
                ),
                (
                    "parent_brand_list",
                    models.JSONField(
                        default=[],
                        max_length=256,
                        verbose_name="Parent Brand List([parent_brand_id])",
                    ),
                ),
                (
                    "mandatory_region",
                    models.JSONField(
                        default=[], max_length=128, verbose_name="Mandatory Region"
                    ),
                ),
                ("max_input_value_number", models.SmallIntegerField(default=1)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_values",
                        to="category.shopeeattribute",
                        verbose_name="Shopee Attribute Value",
                    ),
                ),
            ],
            options={
                "verbose_name": "shopee_attribute_value",
                "verbose_name_plural": "Shopee Attribute Value",
                "db_table": "shopee_attribute_value",
                "ordering": ["-create_time"],
                "unique_together": {("openid", "attribute_id", "value_id")},
            },
        ),
    ]
