# Generated by Django 4.1.1 on 2022-10-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopeeOrderModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                ("order_sn", models.CharField(max_length=50, verbose_name="Order SN")),
                (
                    "order_status",
                    models.CharField(max_length=50, verbose_name="Order Status"),
                ),
                (
                    "total_amount",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Total Amount"
                    ),
                ),
                (
                    "actual_shipping_fee",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Actual Shipping Fee"
                    ),
                ),
                (
                    "waybill_path",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Order Waybill Path",
                    ),
                ),
                (
                    "pay_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Pay Time"
                    ),
                ),
                ("days_to_ship", models.SmallIntegerField(verbose_name="Days To Ship")),
                ("ship_by_date", models.DateTimeField(verbose_name="Ship By Date")),
                (
                    "buyer_user_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Buyer User Id",
                    ),
                ),
                (
                    "buyer_username",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Buyer Username",
                    ),
                ),
                (
                    "handle_status",
                    models.SmallIntegerField(
                        default=1, verbose_name="Order Handle Status"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="store.storemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "shopee_order",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ShopeeOrderRecordModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(max_length=32, verbose_name="Record Batch Number"),
                ),
                ("type", models.SmallIntegerField(verbose_name="Record Type")),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Record Data",
                    ),
                ),
                ("create_time", models.DateTimeField(verbose_name="Create Time")),
                (
                    "shopee_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorded_order",
                        to="order.shopeeordermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "shopee_order_record",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ShopeeOrderPackageModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                ("type", models.SmallIntegerField(verbose_name="Order Package Type")),
                ("uid", models.IntegerField(verbose_name="ForeignKey Unique id")),
                ("quantity", models.IntegerField(default=0, verbose_name="Quantity")),
                (
                    "stock",
                    models.PositiveIntegerField(verbose_name="Stock Of Order Pachage"),
                ),
                ("sku", models.CharField(max_length=50, verbose_name="Replaced Sku")),
                (
                    "image_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Image Url"
                    ),
                ),
                (
                    "shopee_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_order",
                        to="order.shopeeordermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "shopee_order_package",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ShopeeOrderModifyModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                ("modify_type", models.SmallIntegerField(verbose_name="Modify Type")),
                (
                    "global_sku",
                    models.CharField(max_length=50, verbose_name="Global Sku"),
                ),
                (
                    "replaced_id",
                    models.CharField(max_length=50, null=True, verbose_name="Model ID"),
                ),
                (
                    "replaced_sku",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Replaced Sku"
                    ),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="Quantity")),
                (
                    "stock",
                    models.PositiveIntegerField(
                        verbose_name="Stock Of Order Modify Item"
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Image Url"
                    ),
                ),
                (
                    "shopee_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.shopeeordermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "shopee_order_modify",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ShopeeOrderMessageModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                ("message", models.CharField(max_length=500, verbose_name="Message")),
                ("type", models.SmallIntegerField(verbose_name="Message Type")),
                ("mark", models.SmallIntegerField(verbose_name="Order Message Mark")),
                (
                    "shopee_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.shopeeordermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "shopee_order_message",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ShopeeOrderDetailModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        max_length=50, verbose_name="Item’s Unique identifier"
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=250, verbose_name="Item Name"),
                ),
                ("item_sku", models.CharField(max_length=50, verbose_name="Item Sku")),
                (
                    "stock",
                    models.PositiveIntegerField(verbose_name="Stock Of Order Item"),
                ),
                (
                    "model_id",
                    models.CharField(max_length=50, null=True, verbose_name="Model ID"),
                ),
                (
                    "model_name",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Model Name"
                    ),
                ),
                (
                    "model_sku",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Model Sku"
                    ),
                ),
                (
                    "model_quantity_purchased",
                    models.SmallIntegerField(verbose_name="Model Quantity Purchased"),
                ),
                (
                    "model_original_price",
                    models.FloatField(verbose_name="Model Original Price"),
                ),
                (
                    "model_discounted_price",
                    models.FloatField(verbose_name="Model Discounted Price"),
                ),
                (
                    "image_url",
                    models.CharField(max_length=500, verbose_name="Image Url"),
                ),
                (
                    "shopee_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_detail",
                        to="order.shopeeordermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "shoppe_order_detail",
                "verbose_name_plural": "Shoppe Order Detail",
                "db_table": "shopee_order_detail",
                "ordering": ["-id"],
            },
        ),
    ]
