# Generated by Django 4.1.1 on 2022-10-31 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "__first__"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopeeorderdetailmodel",
            name="stock",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_order",
                to="stock.stockrecord",
            ),
        ),
        migrations.AlterField(
            model_name="shopeeordermodifymodel",
            name="stock",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_order_modify",
                to="stock.stockrecord",
            ),
        ),
        migrations.AlterField(
            model_name="shopeeorderpackagemodel",
            name="stock",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_order_package",
                to="stock.stockrecord",
            ),
        ),
    ]
