# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock_bin_gen.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13stock_bin_gen.proto\x12\rstock_bin_gen\x1a\x1bgoogle/protobuf/empty.proto\"-\n\rStockBinModel\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x62in_name\x18\x02 \x01(\t\"\x1a\n\x18StockBinModelListRequest\"*\n\x1cStockBinModelRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x98\x03\n\x17StockBinModelController\x12Q\n\x04List\x12\'.stock_bin_gen.StockBinModelListRequest\x1a\x1c.stock_bin_gen.StockBinModel\"\x00\x30\x01\x12\x46\n\x06\x43reate\x12\x1c.stock_bin_gen.StockBinModel\x1a\x1c.stock_bin_gen.StockBinModel\"\x00\x12W\n\x08Retrieve\x12+.stock_bin_gen.StockBinModelRetrieveRequest\x1a\x1c.stock_bin_gen.StockBinModel\"\x00\x12\x46\n\x06Update\x12\x1c.stock_bin_gen.StockBinModel\x1a\x1c.stock_bin_gen.StockBinModel\"\x00\x12\x41\n\x07\x44\x65stroy\x12\x1c.stock_bin_gen.StockBinModel\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_bin_gen_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOCKBINMODEL._serialized_start=67
  _STOCKBINMODEL._serialized_end=112
  _STOCKBINMODELLISTREQUEST._serialized_start=114
  _STOCKBINMODELLISTREQUEST._serialized_end=140
  _STOCKBINMODELRETRIEVEREQUEST._serialized_start=142
  _STOCKBINMODELRETRIEVEREQUEST._serialized_end=184
  _STOCKBINMODELCONTROLLER._serialized_start=187
  _STOCKBINMODELCONTROLLER._serialized_end=595
# @@protoc_insertion_point(module_scope)
