# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import stock_pb2 as stock__pb2


class StockControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/stock.StockController/List',
                request_serializer=stock__pb2.StockListRequest.SerializeToString,
                response_deserializer=stock__pb2.Stock.FromString,
                )
        self.Create = channel.unary_unary(
                '/stock.StockController/Create',
                request_serializer=stock__pb2.Stock.SerializeToString,
                response_deserializer=stock__pb2.StockCommonResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/stock.StockController/Retrieve',
                request_serializer=stock__pb2.StockRetrieveRequest.SerializeToString,
                response_deserializer=stock__pb2.StockCommonResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/stock.StockController/Update',
                request_serializer=stock__pb2.Stock.SerializeToString,
                response_deserializer=stock__pb2.StockCommonResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/stock.StockController/Destroy',
                request_serializer=stock__pb2.Stock.SerializeToString,
                response_deserializer=stock__pb2.StockCommonResponse.FromString,
                )
        self.Reserve = channel.unary_unary(
                '/stock.StockController/Reserve',
                request_serializer=stock__pb2.StockReserveRequest.SerializeToString,
                response_deserializer=stock__pb2.StockCommonResponse.FromString,
                )
        self.Back = channel.unary_unary(
                '/stock.StockController/Back',
                request_serializer=stock__pb2.StockBackRequest.SerializeToString,
                response_deserializer=stock__pb2.StockCommonResponse.FromString,
                )
        self.Ship = channel.unary_unary(
                '/stock.StockController/Ship',
                request_serializer=stock__pb2.StockShipRequest.SerializeToString,
                response_deserializer=stock__pb2.StockCommonResponse.FromString,
                )


class StockControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reserve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Back(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=stock__pb2.StockListRequest.FromString,
                    response_serializer=stock__pb2.Stock.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=stock__pb2.Stock.FromString,
                    response_serializer=stock__pb2.StockCommonResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=stock__pb2.StockRetrieveRequest.FromString,
                    response_serializer=stock__pb2.StockCommonResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=stock__pb2.Stock.FromString,
                    response_serializer=stock__pb2.StockCommonResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=stock__pb2.Stock.FromString,
                    response_serializer=stock__pb2.StockCommonResponse.SerializeToString,
            ),
            'Reserve': grpc.unary_unary_rpc_method_handler(
                    servicer.Reserve,
                    request_deserializer=stock__pb2.StockReserveRequest.FromString,
                    response_serializer=stock__pb2.StockCommonResponse.SerializeToString,
            ),
            'Back': grpc.unary_unary_rpc_method_handler(
                    servicer.Back,
                    request_deserializer=stock__pb2.StockBackRequest.FromString,
                    response_serializer=stock__pb2.StockCommonResponse.SerializeToString,
            ),
            'Ship': grpc.unary_unary_rpc_method_handler(
                    servicer.Ship,
                    request_deserializer=stock__pb2.StockShipRequest.FromString,
                    response_serializer=stock__pb2.StockCommonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stock.StockController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StockController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/stock.StockController/List',
            stock__pb2.StockListRequest.SerializeToString,
            stock__pb2.Stock.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock.StockController/Create',
            stock__pb2.Stock.SerializeToString,
            stock__pb2.StockCommonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock.StockController/Retrieve',
            stock__pb2.StockRetrieveRequest.SerializeToString,
            stock__pb2.StockCommonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock.StockController/Update',
            stock__pb2.Stock.SerializeToString,
            stock__pb2.StockCommonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock.StockController/Destroy',
            stock__pb2.Stock.SerializeToString,
            stock__pb2.StockCommonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reserve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock.StockController/Reserve',
            stock__pb2.StockReserveRequest.SerializeToString,
            stock__pb2.StockCommonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Back(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock.StockController/Back',
            stock__pb2.StockBackRequest.SerializeToString,
            stock__pb2.StockCommonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stock.StockController/Ship',
            stock__pb2.StockShipRequest.SerializeToString,
            stock__pb2.StockCommonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
