# Generated by Django 4.1.1 on 2022-10-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopeeRegionSettingsModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "area",
                    models.CharField(max_length=50, verbose_name="Country/Region"),
                ),
                (
                    "short_area",
                    models.CharField(
                        max_length=50, verbose_name="Short Country/Region"
                    ),
                ),
                ("currency", models.CharField(max_length=10, verbose_name="Currency")),
                (
                    "exchange_rate",
                    models.FloatField(max_length=50, verbose_name="Exchange Rate"),
                ),
                (
                    "activity_rate",
                    models.FloatField(max_length=50, verbose_name="Activity Rate"),
                ),
                (
                    "commission_rate",
                    models.FloatField(max_length=50, verbose_name="Commission Rate"),
                ),
                (
                    "transaction_rate",
                    models.FloatField(max_length=50, verbose_name="Transaction Rate"),
                ),
                (
                    "withdrawal_rate",
                    models.FloatField(max_length=50, verbose_name="Withdrawal Rate"),
                ),
                (
                    "exchange_loss_rate",
                    models.FloatField(max_length=50, verbose_name="Exchange Loss Rate"),
                ),
                (
                    "buyer_shipping",
                    models.FloatField(max_length=50, verbose_name="Buyer Shipping"),
                ),
                (
                    "other_fee",
                    models.FloatField(max_length=50, verbose_name="Other Fee"),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "shopee_fetch_region_settings",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="StoreModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Store Name")),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        verbose_name="Shop ID Or Merchant ID",
                    ),
                ),
                (
                    "type",
                    models.SmallIntegerField(db_index=True, verbose_name="Store Type"),
                ),
                ("platform", models.SmallIntegerField(verbose_name="Platform Type")),
                ("area", models.CharField(max_length=50, verbose_name="Area Type")),
                (
                    "status",
                    models.SmallIntegerField(default=1, verbose_name="Store Status"),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={
                            models.SmallIntegerField(
                                db_index=True, verbose_name="Store Type"
                            ): 1
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.storemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "store",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="StoreProductModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Store product unique identifier",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=250, verbose_name="Store product Name"),
                ),
                (
                    "product_status",
                    models.CharField(
                        max_length=15, verbose_name="Store product Status"
                    ),
                ),
                (
                    "product_sku",
                    models.CharField(max_length=100, verbose_name="Store product sku"),
                ),
                (
                    "image_url",
                    models.CharField(
                        max_length=500, verbose_name="Store product image url"
                    ),
                ),
                (
                    "category_id",
                    models.IntegerField(verbose_name="Store product thumbnail url"),
                ),
                (
                    "brand_id",
                    models.IntegerField(verbose_name="Store product brand id"),
                ),
                (
                    "brand_name",
                    models.CharField(
                        max_length=100, verbose_name="Store product brand name"
                    ),
                ),
                (
                    "days_to_ship",
                    models.SmallIntegerField(verbose_name="Store product days to ship"),
                ),
                ("weight", models.FloatField(verbose_name="Store product weight")),
                (
                    "length",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Store product length"
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Store product width"
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Store product height"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Store product description"
                    ),
                ),
                (
                    "shop_products",
                    models.ManyToManyField(
                        blank=True,
                        db_table="store_product_relations",
                        limit_choices_to={"store__type__in": [2]},
                        related_name="global_product",
                        to="store.storeproductmodel",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.storemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "store_product",
                "ordering": ["-id"],
                "unique_together": {
                    ("store", "product_sku", "product_status", "product_id")
                },
            },
        ),
        migrations.CreateModel(
            name="StoreProductPackageModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Package Name")),
                ("sku", models.CharField(max_length=50, verbose_name="Package Sku")),
                (
                    "product_type",
                    models.SmallIntegerField(verbose_name="Package Product Type"),
                ),
                (
                    "uid",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Product Unique ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "store_product_package",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="StoreProductVariantModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Store product model unique identifier",
                    ),
                ),
                (
                    "model_sku",
                    models.CharField(
                        max_length=100, verbose_name="Store product model sku"
                    ),
                ),
                (
                    "promotion_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Model promotion id",
                    ),
                ),
                (
                    "option_item_index",
                    models.CharField(max_length=10, verbose_name="Option item index"),
                ),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_variant",
                        to="store.storeproductmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "store_product_variant",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="StoreProductVariantStock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "stock_type",
                    models.SmallIntegerField(default=2, verbose_name="Stock Type"),
                ),
                (
                    "current_stock",
                    models.IntegerField(default=0, verbose_name="Current stock"),
                ),
                (
                    "reserved_stock",
                    models.IntegerField(
                        default=0, verbose_name="Stock reserved for upcoming promotion"
                    ),
                ),
                (
                    "stock_location_id",
                    models.CharField(
                        default="",
                        max_length=16,
                        verbose_name="location_id of the stock",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_stock",
                        to="store.storeproductvariantmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "store_product_variant_stock",
                "verbose_name_plural": "store product variant stock",
                "db_table": "store_product_variant_stock",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="StoreProductPriceInfoModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "type",
                    models.SmallIntegerField(default=2, verbose_name="Price info type"),
                ),
                (
                    "original_price",
                    models.FloatField(
                        max_length=100, verbose_name="Store product original price"
                    ),
                ),
                (
                    "current_price",
                    models.FloatField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Store product current price",
                    ),
                ),
                (
                    "inflated_price_of_original_price",
                    models.FloatField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Inflated price of original price",
                    ),
                ),
                (
                    "inflated_price_of_current_price",
                    models.FloatField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Inflated price of current price",
                    ),
                ),
                (
                    "sip_item_price",
                    models.FloatField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Sip item price",
                    ),
                ),
                (
                    "sip_item_price_source",
                    models.FloatField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Sip item price source",
                    ),
                ),
                ("currency", models.CharField(max_length=10, verbose_name="Currency")),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_price_info",
                        to="store.storeproductmodel",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_price",
                        to="store.storeproductvariantmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "store_product_price_info",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="StoreProductOptionModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Store Product Option Name"
                    ),
                ),
                ("index", models.SmallIntegerField(verbose_name="Option Index")),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_option",
                        to="store.storeproductmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "store_product_option",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="StoreProductOptionItemModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Option Item Name"),
                ),
                (
                    "image_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Option Item Image Url",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Option Item Image Url",
                    ),
                ),
                ("index", models.SmallIntegerField(verbose_name="Option Item Index")),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_option_item",
                        to="store.storeproductmodel",
                    ),
                ),
                (
                    "store_product_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_item",
                        to="store.storeproductoptionmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "store_product_option_item",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="StoreProductMedia",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                ("type", models.SmallIntegerField(verbose_name="Media Type")),
                (
                    "image_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Product image id",
                    ),
                ),
                (
                    "url",
                    models.CharField(max_length=500, verbose_name="Product media url"),
                ),
                ("index", models.SmallIntegerField(verbose_name="Product media index")),
                (
                    "store_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_media",
                        to="store.storeproductmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "store_product_media",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="StorePackageItemModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "uid",
                    models.SmallIntegerField(verbose_name="Item Product Unique ID"),
                ),
                (
                    "product_type",
                    models.SmallIntegerField(verbose_name="Item Product Type"),
                ),
                ("sku", models.CharField(max_length=50, verbose_name="Item Sku")),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_item",
                        to="store.storeproductpackagemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "store_product_package_item",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ShopeeLogisticsCalcModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                ("min_weight", models.FloatField(verbose_name="Min Weight")),
                (
                    "max_weight",
                    models.FloatField(blank=True, null=True, verbose_name="Max Weight"),
                ),
                (
                    "calc_type",
                    models.SmallIntegerField(verbose_name="Logistics Calc Type"),
                ),
                ("logistics_fee", models.FloatField(verbose_name="Logistics Fee")),
                (
                    "interval",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Weight Interval"
                    ),
                ),
                (
                    "region_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="region_logistics_calc",
                        to="store.shopeeregionsettingsmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "shopee_logistics_calc",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StoreInfoModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                ("info_key", models.CharField(max_length=20, verbose_name="Info Key")),
                (
                    "info_value",
                    models.JSONField(max_length=255, verbose_name="Info Value"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.storemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "store_info",
                "ordering": ["-id"],
                "index_together": {("store", "info_key")},
            },
        ),
        migrations.CreateModel(
            name="ShopeeStoreRegionSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "store_uid",
                    models.CharField(max_length=64, verbose_name="Store UID"),
                ),
                (
                    "region_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setting_store",
                        to="store.shopeeregionsettingsmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "shopee_store_profit_setting",
                "verbose_name_plural": "shopee store profit setting",
                "db_table": "shopee_store_profit_setting",
                "ordering": ["id"],
                "unique_together": {("store_uid", "region_settings_id")},
            },
        ),
    ]
