# Generated by Django 4.1.1 on 2022-11-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_storemodel_merchant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storemodel",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    models.SmallIntegerField(
                        db_index=True, verbose_name="Store Type"
                    ): 1
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.storemodel",
            ),
        ),
        migrations.AlterField(
            model_name="storeproductvariantmodel",
            name="model_id",
            field=models.CharField(
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Store product model unique identifier",
            ),
        ),
    ]
