# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import product_pb2 as product__pb2


class ProductControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/product.ProductController/List',
                request_serializer=product__pb2.ProductListRequest.SerializeToString,
                response_deserializer=product__pb2.ProductDetails.FromString,
                )
        self.Create = channel.unary_unary(
                '/product.ProductController/Create',
                request_serializer=product__pb2.ProductDetails.SerializeToString,
                response_deserializer=product__pb2.ProductResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/product.ProductController/Retrieve',
                request_serializer=product__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=product__pb2.ProductResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/product.ProductController/Update',
                request_serializer=product__pb2.Product.SerializeToString,
                response_deserializer=product__pb2.ProductResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/product.ProductController/Destroy',
                request_serializer=product__pb2.Product.SerializeToString,
                response_deserializer=product__pb2.ProductResponse.FromString,
                )
        self.Query = channel.unary_stream(
                '/product.ProductController/Query',
                request_serializer=product__pb2.ProductQueryRequest.SerializeToString,
                response_deserializer=product__pb2.ProductDetails.FromString,
                )
        self.CreateSpecification = channel.unary_unary(
                '/product.ProductController/CreateSpecification',
                request_serializer=product__pb2.Specification.SerializeToString,
                response_deserializer=product__pb2.SpecificationResponse.FromString,
                )


class ProductControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSpecification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=product__pb2.ProductListRequest.FromString,
                    response_serializer=product__pb2.ProductDetails.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=product__pb2.ProductDetails.FromString,
                    response_serializer=product__pb2.ProductResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=product__pb2.RetrieveRequest.FromString,
                    response_serializer=product__pb2.ProductResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=product__pb2.Product.FromString,
                    response_serializer=product__pb2.ProductResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=product__pb2.Product.FromString,
                    response_serializer=product__pb2.ProductResponse.SerializeToString,
            ),
            'Query': grpc.unary_stream_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=product__pb2.ProductQueryRequest.FromString,
                    response_serializer=product__pb2.ProductDetails.SerializeToString,
            ),
            'CreateSpecification': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSpecification,
                    request_deserializer=product__pb2.Specification.FromString,
                    response_serializer=product__pb2.SpecificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/product.ProductController/List',
            product__pb2.ProductListRequest.SerializeToString,
            product__pb2.ProductDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductController/Create',
            product__pb2.ProductDetails.SerializeToString,
            product__pb2.ProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductController/Retrieve',
            product__pb2.RetrieveRequest.SerializeToString,
            product__pb2.ProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductController/Update',
            product__pb2.Product.SerializeToString,
            product__pb2.ProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductController/Destroy',
            product__pb2.Product.SerializeToString,
            product__pb2.ProductResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/product.ProductController/Query',
            product__pb2.ProductQueryRequest.SerializeToString,
            product__pb2.ProductDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateSpecification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product.ProductController/CreateSpecification',
            product__pb2.Specification.SerializeToString,
            product__pb2.SpecificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
