# Generated by Django 4.1.1 on 2022-11-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ListModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Supplier Name",
                    ),
                ),
                (
                    "supplier_city",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Supplier City",
                    ),
                ),
                (
                    "supplier_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Supplier Address",
                    ),
                ),
                (
                    "supplier_contact",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Supplier Contact",
                    ),
                ),
                (
                    "supplier_manager",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Supplier Manager",
                    ),
                ),
                (
                    "supplier_level",
                    models.BigIntegerField(
                        blank=True, default=1, null=True, verbose_name="Supplier Level"
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "supplier",
                "ordering": ["supplier_name"],
            },
        ),
        migrations.CreateModel(
            name="PurchasePlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=1024,
                        null=True,
                        verbose_name="Purchase Plan Image Url",
                    ),
                ),
                ("price", models.FloatField(default=0, verbose_name="Goods Price")),
                ("url", models.CharField(max_length=1024, verbose_name="Goods Url")),
                (
                    "default",
                    models.BooleanField(
                        default=False, verbose_name="Default Purchase Plan"
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        null=True,
                        verbose_name="Purchase Tags",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_purchases",
                        to="supplier.listmodel",
                        verbose_name="Goods Supllier",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchase Plan",
                "verbose_name_plural": "Purchase Plan",
                "db_table": "purchasePlan",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchasePlanGoodsSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "goods",
                    models.PositiveIntegerField(
                        verbose_name="goods id of PurchasePlan"
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Goods Purchase Plan Level"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goods_settings",
                        to="supplier.purchaseplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "purchasePlan_goods_setting",
                "verbose_name_plural": "Purchase Plan Goods Setting",
                "db_table": "purchasePlan_goods_setting",
                "ordering": ["-id"],
                "unique_together": {("goods", "level")},
            },
        ),
    ]
