# Generated by Django 4.1.1 on 2022-11-03 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0011_alter_storemodel_merchant"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalProductRelations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "global_product_id",
                    models.CharField(max_length=128, verbose_name="Global Product Id"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopee_product",
                        to="store.storeproductmodel",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_store",
                        to="store.storemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "global_product_relations",
                "verbose_name_plural": "Global Product Relations",
                "db_table": "global_product_relations",
                "ordering": ["-create_time"],
            },
        ),
    ]
