# Generated by Django 4.1.1 on 2022-11-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGoodsRelations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "goods_id",
                    models.PositiveIntegerField(verbose_name="Goods id of product"),
                ),
                (
                    "publish_id",
                    models.PositiveIntegerField(verbose_name="Publish id of Shopee"),
                ),
            ],
            options={
                "verbose_name": "product_goods_relations",
                "verbose_name_plural": "Shopee Product Goods Relations",
                "db_table": "product_goods_relations",
                "ordering": ["-id"],
            },
        ),
    ]
