# Generated by Django 4.1.1 on 2022-11-01 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsnListModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                ("asn_code", models.CharField(max_length=255, verbose_name="ASN Code")),
                (
                    "asn_status",
                    models.BigIntegerField(default=0, verbose_name="ASN Status"),
                ),
                (
                    "total_qty",
                    models.BigIntegerField(default=0, verbose_name="Goods Quantity"),
                ),
                (
                    "total_weight",
                    models.FloatField(default=0, verbose_name="Total Weight"),
                ),
                ("total_cost", models.FloatField(default=0, verbose_name="Total Cost")),
                ("bar_code", models.CharField(max_length=255, verbose_name="Bar Code")),
                ("amend", models.BooleanField(default=False, verbose_name="Amend Asn")),
                (
                    "supplier",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppler_asn",
                        to="supplier.listmodel",
                        verbose_name="ASN Supllier",
                    ),
                ),
            ],
            options={
                "verbose_name": "data id",
                "verbose_name_plural": "data id",
                "db_table": "asnlist",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="AsnOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Asn Order Url",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "未发货"),
                            (1, "运输中"),
                            (2, "已到达"),
                            (3, "已签收"),
                            (-1, "已退回"),
                        ],
                        default=0,
                        verbose_name="Order status",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        null=True,
                        verbose_name="Delivery Date",
                    ),
                ),
                (
                    "trans_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Transportation Name"
                    ),
                ),
                (
                    "trans_url",
                    models.CharField(
                        default="", max_length=512, verbose_name="Transportation Url"
                    ),
                ),
                (
                    "trans_phone",
                    models.CharField(
                        default="", max_length=128, verbose_name="Transportation Phone"
                    ),
                ),
                (
                    "item_cost",
                    models.FloatField(default=0, verbose_name="Order Item Cost"),
                ),
                (
                    "trans_fee",
                    models.FloatField(default=0, verbose_name="Order Transport fess"),
                ),
                (
                    "discount",
                    models.FloatField(default=0, verbose_name="Order discount"),
                ),
                (
                    "asn",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asn_order",
                        to="asn.asnlistmodel",
                        verbose_name="ASN",
                    ),
                ),
            ],
            options={
                "verbose_name": "asnorder",
                "verbose_name_plural": "asn order",
                "db_table": "asnorder",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AsnDetailModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creater",
                    models.CharField(max_length=255, verbose_name="Who created"),
                ),
                ("openid", models.CharField(max_length=255, verbose_name="Openid")),
                (
                    "is_delete",
                    models.BooleanField(default=False, verbose_name="Delete Label"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Update Time"
                    ),
                ),
                (
                    "goods",
                    models.PositiveIntegerField(verbose_name="Goods Id of AsnDetail"),
                ),
                ("goods_qty", models.IntegerField(default=0, verbose_name="Goods QTY")),
                (
                    "goods_actual_qty",
                    models.IntegerField(default=0, verbose_name="Goods Actual QTY"),
                ),
                (
                    "goods_shortage_qty",
                    models.IntegerField(default=0, verbose_name="Goods Shortage QTY"),
                ),
                (
                    "goods_more_qty",
                    models.IntegerField(default=0, verbose_name="Goods More QTY"),
                ),
                (
                    "goods_damage_qty",
                    models.IntegerField(default=0, verbose_name="Goods damage QTY"),
                ),
                ("goods_cost", models.FloatField(default=0, verbose_name="Goods Cost")),
                (
                    "sorted",
                    models.BooleanField(default=False, verbose_name="Is Sorted"),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(verbose_name="Stock Id of AsnDetail"),
                ),
                (
                    "asn",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asn_details",
                        to="asn.asnlistmodel",
                        verbose_name="ASN",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_asn_details",
                        to="supplier.purchaseplan",
                        verbose_name="Asn Detail Purchase ",
                    ),
                ),
            ],
            options={
                "verbose_name": "AsnDetailModel",
                "verbose_name_plural": "Asn Detail Model",
                "db_table": "asndetail",
                "ordering": ["-id"],
            },
        ),
    ]
