# Generated by Django 4.1.1 on 2022-11-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
        ("asn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asndetailmodel",
            name="stock",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_asn_detail",
                to="stock.stockrecord",
            ),
        ),
    ]
